/******************************************
Treehouse FSJS Techdegree:
project 1 - A Random Quote Generator
******************************************/

var randomNumber;    // Variable to store random number generated by getRandomQuote();
var randumQuote;     // Variable to store random quote generated by getRandomQuote();


/*** 
  An array of objects that can contain up to 4 properties: 
    quote: The quote that will be presented to the user
    source: The person who said the quote
    citation: The content source of the quote (aka interview, book, ect.)
    year: The year the quote originated 
***/

var quotes = [
  {
    quote: "Don’t compare yourself with anyone in this world…if you do so, you are insulting yourself." , 
    source: "Bill Gates",
  }, 
  {
    quote: "When something is important enough, you do it even if the odds are not in your favor.", 
    source: "Elon Musk",
  }, 
  {
    quote: "No matter what people tell you, words and ideas can change the world.", 
    source: "Robin Williams",
  }, 
  {
    quote: "The world needs a sense of worth, and it will achieve it only by its people feeling that they are worthwhile.", 
    source: "Fred Rogers",
  }, 
  {
    quote: "It's kind of fun to do the impossible.", 
    source: "Walt Disney",
  }, 
  {
    quote: "I haven’t failed. I’ve just found 10,000 ways that won’t work.", 
    source: "Thomas Edison",
  }, 
  {
    quote: "Anyone who stops learning is old, whether at twenty or eighty. Anyone who keeps learning stays young. The greatest thing in life is to keep your mind young.", 
    source: "Henry Ford",
  }, 
  {
    quote: "Happiness is not a goal; it is a by-product.", 
    source: "Eleanor Roosevelt",
  }, 
  {
    quote: "...with great power there must also come -- great responsibility!", 
    source: "Stan Lee",
    citation: "Amazing Fantasy #15", 
    year: "1962",
  }, 
  {
    quote: "Find something that makes you happy and go for it.", 
    source: "Zendaya",
  }
]

console.log(quotes);


/***
`getRandomQuote`
   - uses the randomNumber variable to store a random number between 0 and then length of the array 'quotes'
   - returns a random quote from the 'quotes' array using the randomNumber variable
***/

function getRandomQuote(){
  randomNumber = Math.floor(Math.random() * quotes.length)
  return quotes[randomNumber];
}

console.log(getRandomQuote());


/***
  Create the `printQuote` function to: 
   - Call the `getRandomQuote` function and assign it to a variable.
   - Create a variable for the HTML string and set it equal to an empty string.
   - Use the HTML template in the instructions or the markup in the index.html file, AND 
     the random quote vairable to build your HTML string.
   - Add the quote and source section to the HTML string.
   - Use an if statement to check for the citation property before adding it to the HTML string.
   - Use an if statement to check for the year property before adding it to the HTML string.
   - Don't forget to close that final `p` tag.
   - Set the `innerHTML` of the `quote-box` div to the HTML string. 
***/

function printQuote(quote) {
  var finalQuote = ''; // Variable to store the final quote to be produced using printRandomQuote();
  randomQuote = getRandomQuote();
  finalQuote += '<p class="quote"> ' + randomQuote.quote + '</p>';
  finalQuote += '<p class="source"> ' + randomQuote.source; 

  if (randomQuote.citation){
    finalQuote += '<span class="citation"> ' + randomQuote.citation + '</span>';
  }

  if (randomQuote.year){
    finalQuote += '<span class="year"> ' + randomQuote.year + '</span>';
  }

  finalQuote += '</p>';

  document.getElementById('quote-box').innerHTML = finalQuote;
}


/***
  When the "Show another quote" button is clicked, the event listener 
  below will be triggered, and it will call, or "invoke", the `printQuote` 
  function. So do not make any changes to the line of code below this 
  comment.
***/

document.getElementById('loadQuote').addEventListener("click", printQuote, false);


// Remember to delete the comments that came with this file, and replace them with your own code comments.